### ISSUE TITLE
code & data

### ISSUE THREAD

**Issue by Xnhyacinth** [C-W-D/CasCoD#2]
Thank you very much to the author for updating the code and data so quickly. However, I have a small question. It appears that the code contains some bugs in certain places. For example, the file `src/utils/dataset_utils.py` does not have functions such as `get_alpaca_dataset`, and there does not seem to be a BBH dataset corresponding to the Scott dataset. Is it possible that these functions and datasets have not been uploaded, or is it that the code has not been fully updated?

Thanks a lot.

**Comment by C-W-D** [comment]
Thank you for your attention. I apologize for the error caused by my oversight and have updated the `dataset_utils` file by removing the unnecessary functions. The `LLMSCOTTDataset ` does exist, and it can be found in `bbh_dataset.py ` (Line 385).

**Comment by Xnhyacinth** [comment]
Thank you very much. Scott mentioned above is the dataset "all_task_train_final_only_right.json". I see that this is referenced in the code, but it does not appear to be in the `dataset/bbh/bbh_all_data` directory.

**Comment by C-W-D** [comment]
okay, i have updated that.

**Comment by Xnhyacinth** [comment]
Thanks a lot.

**Comment by Xnhyacinth** [comment]
Hi, there are some problems about 'where is prompt_for_vanilla/prompt_3shotcot_for_vanilla.txt'. It is missing.

**Comment by C-W-D** [comment]
I have updated that, thanks.

**Comment by Xnhyacinth** [comment]
Maybe your data about arc-c and arc-e are incomplete? Or we need to change the corresponding code to test these two data sets? 
@C-W-D

**Comment by C-W-D** [comment]
@Xnhyacinth The arc-c and arc-e are in the JSON format of the original dataset. You need to further convert them into a parseable JSON file with the same keys as the test dataset in AGIEval. In this conversion, the instruction and output fields should correspond to the input and target fields of the original dataset, respectively. You can set the remaining fields as you see fit; they will not affect the evaluation results. The prompt and response fields actually store the input and output results of ChatGPT in a zero-shot setting.

P.S. Due to the confidential nature of our research institute, all complete resources of this project are stored on internal servers. However, copying them out requires cumbersome procedures. The core code of the publicly available repository should be fine. If you encounter any issues, please feel free to communicate at any time.

**Comment by Xnhyacinth** [comment]
Ok, I know it. Thanks a lot.

**Comment by Xnhyacinth** [comment]
The previous problem was test. Now the problem of fine-tuning is that `scott` method and `answer-sft` method have not been properly handled. Specifically, it is the data processing part corresponding to `scott`, without 'pos' and' neg 'keys' in `bbh_dataset.py`. And answer-sft has no corresponding training function in `'train_utils.py'`.

**Comment by C-W-D** [comment]
For answer sft, see lines 193-196 in `train_utils.py`. Maybe I didn't handle it properly when I sorted out the code later (Line 92). In addition, I updated Scott's training data.

**Comment by Xnhyacinth** [comment]
Sure. It is all fine.
